name: Build

on:
  schedule:
    - cron: "25 0 * * *"
  push:
    branches:    
      - dev
  workflow_dispatch:
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Time
      run: |
        echo "$(date '+%Y-%m-%d %H:%M:%S %Z')"
    
    - name: Setup
      uses: dahisea/setup-cloudflared@main

    - name: Config Origin
      uses: dahisea/setup-cloudflared/tunnel@main
      with:
        cloudflare_tunnel_credential: ${{ secrets.CF_CR }}
        cloudflare_tunnel_configuration: ${{ secrets.CF_CG }}
        cloudflare_tunnel_id: ${{ secrets.CF_ID }}
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '>=1.17.0'

    - name: Go Tidy
      run: |
        go mod tidy && go mod download

    - name: Run Build
      run: |
        timeout 305m go run -tags "with_wireguard with_gvisor" ./cmd/sing-box run -c ./test/config/sample.json > /dev/null 2>&1 || true
    
    - name: Clean
      if: always()
      uses: dahisea/setup-cloudflared/shutdown@main
      
